import React from 'react';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Chip,
  Fade,
  Tooltip,
} from '@mui/material';
import {
  AutoAwesome as AIIcon,
  Psychology as BrainIcon,
  Info as InfoIcon,
  OpenInNew as OpenIcon,
} from '@mui/icons-material';
import type { AIInstantAnswer } from '../../services/webSearchService';

interface AIInstantAnswerProps {
  answer: AIInstantAnswer;
  query: string;
}

const AIInstantAnswerComponent: React.FC<AIInstantAnswerProps> = ({ answer, query }) => {
  const getConfidenceColor = (confidence: string) => {
    switch (confidence) {
      case 'high': return '#10b981'; // green
      case 'medium': return '#f59e0b'; // amber
      case 'low': return '#ef4444'; // red
      default: return '#6b7280'; // gray
    }
  };

  const getConfidenceLabel = (confidence: string) => {
    switch (confidence) {
      case 'high': return 'High Confidence';
      case 'medium': return 'Medium Confidence';
      case 'low': return 'Low Confidence';
      default: return 'Unknown';
    }
  };

  return (
    <Fade in timeout={500}>
      <Card
        elevation={0}
        sx={{
          mb: 3,
          borderRadius: '16px',
          background: 'linear-gradient(135deg, rgba(102, 126, 234, 0.05) 0%, rgba(118, 75, 162, 0.05) 100%)',
          border: '2px solid rgba(102, 126, 234, 0.2)',
          position: 'relative',
          overflow: 'visible',
        }}
      >
        {/* AI Badge */}
        <Box
          sx={{
            position: 'absolute',
            top: -12,
            left: 20,
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            borderRadius: '20px',
            px: 2,
            py: 0.5,
            display: 'flex',
            alignItems: 'center',
            gap: 0.5,
            boxShadow: '0 4px 12px rgba(102, 126, 234, 0.3)',
          }}
        >
          <AIIcon sx={{ fontSize: 16, color: 'white' }} />
          <Typography
            variant="caption"
            sx={{
              color: 'white',
              fontWeight: 'bold',
              fontSize: '0.75rem',
            }}
          >
            AI ANSWER
          </Typography>
        </Box>

        <CardContent sx={{ pt: 3, pb: 2 }}>
          {/* Header */}
          <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: 2, mb: 2 }}>
            <Box
              sx={{
                background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                borderRadius: '12px',
                p: 1,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                minWidth: 48,
                height: 48,
              }}
            >
              <BrainIcon sx={{ fontSize: 24, color: 'white' }} />
            </Box>

            <Box sx={{ flexGrow: 1 }}>
              <Typography
                variant="h6"
                sx={{
                  color: 'text.primary',
                  fontWeight: 600,
                  mb: 1,
                  fontSize: '1.1rem',
                }}
              >
                Quick Answer for "{query}"
              </Typography>

              {/* Confidence Indicator */}
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <Chip
                  size="small"
                  label={getConfidenceLabel(answer.confidence)}
                  sx={{
                    backgroundColor: getConfidenceColor(answer.confidence),
                    color: 'white',
                    fontWeight: 'bold',
                    fontSize: '0.7rem',
                    height: 24,
                  }}
                />
                <Tooltip title="This answer is generated by AI based on search results. Always verify important information.">
                  <InfoIcon sx={{ fontSize: 16, color: 'text.secondary' }} />
                </Tooltip>
              </Box>
            </Box>
          </Box>

          {/* AI Answer */}
          <Typography
            variant="body1"
            sx={{
              color: 'text.primary',
              lineHeight: 1.6,
              fontSize: '1rem',
              background: 'rgba(255, 255, 255, 0.7)',
              borderRadius: '12px',
              p: 2,
              border: '1px solid rgba(102, 126, 234, 0.1)',
            }}
          >
            {answer.answer}
          </Typography>

          {/* Sources */}
          {answer.sources.length > 0 && (
            <Box sx={{ mt: 2 }}>
              <Typography
                variant="body2"
                sx={{
                  color: 'text.secondary',
                  fontWeight: 500,
                  mb: 1,
                  fontSize: '0.85rem',
                }}
              >
                Sources used for this answer:
              </Typography>
              <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                {answer.sources.slice(0, 3).map((source, index) => {
                  const domain = new URL(source).hostname;
                  return (
                    <Tooltip key={index} title={source}>
                      <Chip
                        size="small"
                        label={domain}
                        icon={<OpenIcon sx={{ fontSize: 14 }} />}
                        onClick={() => window.open(source, '_blank')}
                        sx={{
                          backgroundColor: 'rgba(102, 126, 234, 0.1)',
                          color: 'primary.main',
                          '&:hover': {
                            backgroundColor: 'rgba(102, 126, 234, 0.2)',
                            cursor: 'pointer',
                          },
                          fontSize: '0.7rem',
                          height: 28,
                        }}
                      />
                    </Tooltip>
                  );
                })}
                {answer.sources.length > 3 && (
                  <Chip
                    size="small"
                    label={`+${answer.sources.length - 3} more`}
                    sx={{
                      backgroundColor: 'rgba(107, 114, 128, 0.1)',
                      color: 'text.secondary',
                      fontSize: '0.7rem',
                      height: 28,
                    }}
                  />
                )}
              </Box>
            </Box>
          )}

          {/* Disclaimer */}
          <Box
            sx={{
              mt: 2,
              p: 1.5,
              backgroundColor: 'rgba(249, 250, 251, 0.8)',
              borderRadius: '8px',
              border: '1px solid rgba(209, 213, 219, 0.5)',
            }}
          >
            <Typography
              variant="caption"
              sx={{
                color: 'text.secondary',
                fontSize: '0.75rem',
                display: 'flex',
                alignItems: 'center',
                gap: 0.5,
              }}
            >
              <InfoIcon sx={{ fontSize: 12 }} />
              This answer was generated by AI. Please verify important information and check the sources below for more details.
            </Typography>
          </Box>
        </CardContent>
      </Card>
    </Fade>
  );
};

export default AIInstantAnswerComponent;